/** Canvas reducer with undo/redo. Pure: ids are generated by callers, never in here. */
import { GRID, canConnect, uid, type CanvasDoc, type CanvasEdge, type CanvasNode } from './model';

const HISTORY_LIMIT = 100;

export interface CanvasState {
  doc: CanvasDoc;
  past: CanvasDoc[];
  future: CanvasDoc[];
  selection: string[];
  selectedEdge: string | null;
  /** Snapshot taken when a drag starts; committed to history once on release. */
  txn: CanvasDoc | null;
}

export type CanvasAction =
  | { type: 'insert'; nodes: CanvasNode[]; edges?: CanvasEdge[]; select?: boolean }
  | { type: 'begin' }
  | { type: 'move'; positions: Record<string, { x: number; y: number }> }
  | { type: 'commit' }
  | { type: 'nudge'; dx: number; dy: number }
  | { type: 'connect'; edge: CanvasEdge }
  | { type: 'delete' }
  | { type: 'select'; ids: string[] }
  | { type: 'selectAll' }
  | { type: 'selectEdge'; id: string | null }
  | { type: 'undo' }
  | { type: 'redo' }
  | { type: 'replace'; doc: CanvasDoc };

export const createInitialState = (doc: CanvasDoc): CanvasState => ({
  doc,
  past: [],
  future: [],
  selection: [],
  selectedEdge: null,
  txn: null,
});

function record(state: CanvasState, doc: CanvasDoc): CanvasState {
  if (doc === state.doc) return state;
  return { ...state, doc, past: [...state.past, state.doc].slice(-HISTORY_LIMIT), future: [] };
}

function keepExisting(ids: string[], doc: CanvasDoc): string[] {
  const alive = new Set(doc.nodes.map((n) => n.id));
  return ids.filter((id) => alive.has(id));
}

export function canvasReducer(state: CanvasState, action: CanvasAction): CanvasState {
  switch (action.type) {
    case 'insert': {
      const doc = {
        nodes: [...state.doc.nodes, ...action.nodes],
        edges: [...state.doc.edges, ...(action.edges ?? [])],
      };
      const next = record(state, doc);
      return action.select ? { ...next, selection: action.nodes.map((n) => n.id), selectedEdge: null } : next;
    }
    case 'begin':
      return { ...state, txn: state.doc };
    case 'move': {
      let changed = false;
      const nodes = state.doc.nodes.map((n) => {
        const p = action.positions[n.id];
        if (!p || (p.x === n.x && p.y === n.y)) return n;
        changed = true;
        return { ...n, x: p.x, y: p.y };
      });
      return changed ? { ...state, doc: { ...state.doc, nodes } } : state;
    }
    case 'commit': {
      if (!state.txn) return state;
      if (state.txn === state.doc) return { ...state, txn: null };
      return {
        ...state,
        txn: null,
        past: [...state.past, state.txn].slice(-HISTORY_LIMIT),
        future: [],
      };
    }
    case 'nudge': {
      if (!state.selection.length) return state;
      const selected = new Set(state.selection);
      return record(state, {
        ...state.doc,
        nodes: state.doc.nodes.map((n) => (selected.has(n.id) ? { ...n, x: n.x + action.dx, y: n.y + action.dy } : n)),
      });
    }
    case 'connect': {
      if (!canConnect(state.doc, action.edge.from, action.edge.to)) return state;
      return { ...record(state, { ...state.doc, edges: [...state.doc.edges, action.edge] }), selectedEdge: null };
    }
    case 'delete': {
      if (state.selectedEdge) {
        const doc = { ...state.doc, edges: state.doc.edges.filter((e) => e.id !== state.selectedEdge) };
        return { ...record(state, doc), selectedEdge: null };
      }
      if (!state.selection.length) return state;
      const selected = new Set(state.selection);
      const doc = {
        nodes: state.doc.nodes.filter((n) => !selected.has(n.id)),
        edges: state.doc.edges.filter((e) => !selected.has(e.from) && !selected.has(e.to)),
      };
      return { ...record(state, doc), selection: [] };
    }
    case 'select':
      return { ...state, selection: action.ids, selectedEdge: null };
    case 'selectAll':
      return { ...state, selection: state.doc.nodes.map((n) => n.id), selectedEdge: null };
    case 'selectEdge':
      return { ...state, selectedEdge: action.id, selection: action.id ? [] : state.selection };
    case 'undo': {
      const previous = state.past[state.past.length - 1];
      if (!previous) return state;
      return {
        ...state,
        doc: previous,
        past: state.past.slice(0, -1),
        future: [state.doc, ...state.future].slice(0, HISTORY_LIMIT),
        selection: keepExisting(state.selection, previous),
        selectedEdge: null,
        txn: null,
      };
    }
    case 'redo': {
      const next = state.future[0];
      if (!next) return state;
      return {
        ...state,
        doc: next,
        past: [...state.past, state.doc].slice(-HISTORY_LIMIT),
        future: state.future.slice(1),
        selection: keepExisting(state.selection, next),
        selectedEdge: null,
        txn: null,
      };
    }
    case 'replace':
      return { ...record(state, action.doc), selection: [], selectedEdge: null };
  }
}

/** Clones the selection (and edges between selected nodes) with fresh ids. */
export function duplicateSelection(state: CanvasState, offset = GRID * 2) {
  const selected = new Set(state.selection);
  if (!selected.size) return null;
  const idMap = new Map<string, string>();
  const nodes = state.doc.nodes
    .filter((n) => selected.has(n.id))
    .map((n) => {
      const id = uid('n');
      idMap.set(n.id, id);
      return { ...n, id, x: n.x + offset, y: n.y + offset };
    });
  const edges = state.doc.edges
    .filter((e) => idMap.has(e.from) && idMap.has(e.to))
    .map((e) => ({ id: uid('e'), from: idMap.get(e.from)!, to: idMap.get(e.to)! }));
  return { nodes, edges };
}
